### ISSUE TITLE
Having issue with www.google.com

### ISSUE THREAD

**Issue by qiujiangkun** [Nv7-GitHub/googlesearch#1]
I'm trying to fetch google search results via a socks5 proxy. However, I encountered this. I can access google via requests.get(), though.
```python
search('Zhang, Hongzhang CAS - Dalian Institute of Chemical Physics')
```
```log
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=Zhang,+Hongzhang+CAS+-+Dalian+Institute+of+Chemical+Physics&num=11&hl=en (Caused by SSLError(SSLCertVerificationError("hostname 'www.google.com' doesn't match either of 'dropbox.com', 'www.dropbox.com', 'support.dropbox.com', 'live.dropbox.com', 'opensource.dropbox.com', 'linux.dropbox.com', 'texter.dropbox.com'")))
```

**Comment by Nv7-GitHub** [comment]
I will look into that when I have access to a good development environment. Thank you for reporting this!

**Comment by Nv7-GitHub** [comment]
Sorry for the long reply, I tried that and it worked on my computer. Maybe something is wrong with your computer? What happens if you try again?

**Comment by qiujiangkun** [comment]
It's probably because of my proxy settings. The issue has been solved
