### ISSUE TITLE
Newest changes have not yet been released on Pypi

### ISSUE THREAD

**Issue by DenverCoder1** [Nv7-GitHub/googlesearch#12]
Hi @Nv7-GitHub,

I've been using this package, but by using it, it is preventing me from upgrading my beatifulsoup4 dependency from 4.9.1 to 4.9.3 since the released version of this package depends on 4.9.1.

The current requirements.txt requests beatifulsoup4 4.9.3, but this version of the file is not released on Pypi and cannot be installed with pip.

If you have the time, it would be great if you would be able to publish a new release.

You may want to consider a GitHub action to [upload a Python Package using Twine when a release is created](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries).

You may also want to consider [adding Dependabot](https://dev.to/denvercoder1/keeping-your-dependencies-updated-automatically-with-dependabot-299g) for more easily updating dependency versions.

Let me know if I can help with anything.

**Comment by Nv7-GitHub** [comment]
Sorry, I wanted to merge https://github.com/Nv7-GitHub/googlesearch/pull/7 before updating on PyPi but haven't gotten around to testing its code, my Python versions are all mismatched :(, but hopefully I'll be able to update it soon

**Comment by DenverCoder1** [comment]
No problem, there's no need to rush. It is fine if it takes some time. :)

**Comment by Nv7-GitHub** [comment]
Pushed them! Sorry for how long it took, been busy with other projects :(

**Comment by DenverCoder1** [comment]
Thanks!
