### ISSUE TITLE
why doesn't this search code work?

### ISSUE THREAD

**Issue by ioanf2** [Nv7-GitHub/googlesearch#14]
```
import json
import random
import re
import requests
from bs4 import BeautifulSoup

try:
        from googlesearch import search
        search("My name is Prince", num_results=100, lang="fr")  #search on google "My name is Prince"

        print(search)

except ImportError:
    print("No module named 'google' found")

    for j in search(query, tld="co", num=10, stop=10, pause=2):
         print(j)
```

**Comment by ioanf2** [comment]
yes, I install the library. Seems that nothing happen when I run the code. 

See this print screen:  

[https://snipboard.io/A3E1R7.jpg](https://snipboard.io/A3E1R7.jpg)

**Comment by Nv7-GitHub** [comment]
Ah, figured it out! You have to do
```python
import json
import random
import re
import requests
from bs4 import BeautifulSoup

try:
        from googlesearch import search
        results = search("My name is Prince", num_results=100, lang="fr")  #search on google "My name is Prince"

        print(results)

except ImportError:
    print("No module named 'google' found")

    for j in search(query, tld="co", num=10, stop=10, pause=2):
         print(j)
```
You were just printing the function `search` instead of the search results.

**Comment by ioanf2** [comment]
works, thanks. 

By the way,  is there is any possibility to search google with operators, such as **" * "**  or **"my name AROUND(7) Prince"** ?

**Comment by Nv7-GitHub** [comment]
there might be a way, I know that Google has some options that you can put in the query string like `site:`, however this would most likely have to be a Google feature. This library just processes Google's results, and sends the query string to google, so anything you can do with the Google search box you can do with this lib

**Comment by Nv7-GitHub** [comment]
Going to close this issue
