### ISSUE TITLE
maximum number of results returned

### ISSUE THREAD

**Issue by luke4u** [Nv7-GitHub/googlesearch#17]
Hi there,

thank you for this brilliant dev work. just a minor thing, I noticed that the maximum number of results seems to be 100.

below is the simple line to run:

`search('data', 500)`

would be possible to help why and enable higher limit? 

Thank you so much. 
L

**Comment by Nv7-GitHub** [comment]
It currently doesn't support google's pagination, I plan on fixing it in the rewrite but haven't gotten around to that 😔

**Comment by luke4u** [comment]
alright thank you! I do look forward to more of your brilliant work!
