### ISSUE TITLE
search specific (e.g. google news)

### ISSUE THREAD

**Issue by CarlosGrat** [Nv7-GitHub/googlesearch#24]
is there anyway to search through a specific section of google such as google news or google finance? I tried changing the init file where
url="https://www.news.google.com/search",

*added news between www and google*
is it not that simple, sorry for noob question!
there was no end to it, it would just continue to run

**Comment by Nv7-GitHub** [comment]
Unfortunately this won't work because Google News and Google Finance have different UIs, so the current HTML extraction won't work on it. This is probably better to do with a separate library.
