### ISSUE TITLE
Will my IP address be block by google if I perform 5 searches every 30 seconds? 

### ISSUE THREAD

**Issue by OAT7963** [Nv7-GitHub/googlesearch#25]

**Comment by Themis3000** [comment]
There is no clear answer on rate limits provided by google, so all we can do is speculate and use trial and error. I've heard extremely mixed results with some people reporting the ability to do a few 100 searches a day without limits and others reporting under 15 a day.

5 searches back to back seems very high though, even 1 search every 30 seconds seems like quite a lot to me. I don't think that amount will work out for you. If you do get rate limited, your ip won't actually be blocked so there is little harm in trying. You may just have to start doing captchas more often for a little bit.

**Comment by OAT7963** [comment]
Thanks for the informative reply. Appreciate it
