### ISSUE TITLE
generator object search at (solved)

### ISSUE THREAD

**Issue by vapperworld** [Nv7-GitHub/googlesearch#28]
Hi! i try this code:

>>> from googlesearch import search
>>> search("Google", num_results=100)

and, this is the response:

<generator object search at 0x000001C366222960> 

any idea?
thanks

**Comment by vapperworld** [comment]
Auto Solved....🤭

from googlesearch import search
list(search("Google", num_results=100))

results in :

['https://www.google.com/', 'https://www.google.com/', 'https://www.google.es/', 'https://blog.google/', 'https://about.google/', 'https://en.wikipedia.org/wiki/Google', 'https://www.linkedin.com/company/google', 'https://www.facebook.com/Google/', 'https://safety.google/', 'https://grow.google/certificates/', 'https://www.xataka.com/empresas-y-economia/no-habra-rival-para-buscador-google-porque-alphabet-mato-incentivos-para-crearlo']

**Comment by 0932test** [comment]
How to solve? I have this problem after updating my computer

**Comment by Themis3000** [comment]
> How to solve? I have this problem after updating my computer

`search(your params)` returns a generator, not a list.

`list(search(your params))` turns the generator returned into a list.

**Comment by 0932test** [comment]
> > How to solve? I have this problem after updating my computer
> 
> `search(your params)` returns a generator, not a list.
> 
> `list(search(your params))` turns the generator returned into a list.

my code:
from googlesearch import search
import pprint

list = search("google")
pprint.pprint(list)


<generator object search at 0x105c57190>

**Comment by Themis3000** [comment]
> > > How to solve? I have this problem after updating my computer
> > 
> > 
> > `search(your params)` returns a generator, not a list.
> > `list(search(your params))` turns the generator returned into a list.
> 
> my code: from googlesearch import search import pprint
> 
> list = search("google") pprint.pprint(list)
> 
> <generator object search at 0x105c57190>

Change your code to look like the following:

```python
from googlesearch import search
import pprint

list = list(search("google"))
pprint.pprint(list)
```

when you use search() it gives you a generator

so you need to put the result of search() into list() to turn it into a list.

**Comment by 0932test** [comment]
> > > > How to solve? I have this problem after updating my computer
> > > 
> > > 
> > > `search(your params)` returns a generator, not a list.
> > > `list(search(your params))` turns the generator returned into a list.
> > 
> > 
> > my code: from googlesearch import search import pprint
> > list = search("google") pprint.pprint(list)
> > <generator object search at 0x105c57190>
> 
> Change your code to look like the following:
> 
> ```python
> from googlesearch import search
> import pprint
> 
> list = list(search("google"))
> pprint.pprint(list)
> ```
> 
> when you use search() it gives you a generator
> 
> so you need to put the result of search() into list() to turn it into a list.

Great, it's resolved. Thanks!

**Comment by Themis3000** [comment]
> > > > > How to solve? I have this problem after updating my computer
> > > > 
> > > > 
> > > > `search(your params)` returns a generator, not a list.
> > > > `list(search(your params))` turns the generator returned into a list.
> > > 
> > > 
> > > my code: from googlesearch import search import pprint
> > > list = search("google") pprint.pprint(list)
> > > <generator object search at 0x105c57190>
> > 
> > 
> > Change your code to look like the following:
> > ```python
> > from googlesearch import search
> > import pprint
> > 
> > list = list(search("google"))
> > pprint.pprint(list)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when you use search() it gives you a generator
> > so you need to put the result of search() into list() to turn it into a list.
> 
> Great, it's resolved. Thanks!

No problem, glad to help! Happy coding!

**Comment by Nv7-GitHub** [comment]
Note that if you requested a lot of results, turning it into a list may send many requests
