### ISSUE TITLE
Does not get first result

### ISSUE THREAD

**Issue by joofio** [Nv7-GitHub/googlesearch#31]
Hi,
These lines over here: https://github.com/Nv7-GitHub/googlesearch/blob/v1.1.0/googlesearch/__init__.py#L48-L54 stop the package from retrieving the first result, which unfortunately is usually the correct...

**Comment by Nv7-GitHub** [comment]
Could you submit a PR showing how to fix this?

**Comment by SaadEGI** [comment]
> Hi, These lines over here: https://github.com/Nv7-GitHub/googlesearch/blob/v1.1.0/googlesearch/__init__.py#L48-L54 stop the package from retrieving the first result, which unfortunately is usually the correct...

are you looking to get the first result from google search?

**Comment by joofio** [comment]
The thing is: When i search for a certain term in google (in the browser), sometimes the first results appears with a "special" div which is not captured by the package. like a featured result

**Comment by Nv7-GitHub** [comment]
Solved in 085e984fbbd77fe23b4bfb2cfdbb11ab0b43c1d1
