### ISSUE TITLE
search() gets stuck on infinite "while loop" if the search term has zero results

### ISSUE THREAD

**Issue by Tomz295** [Nv7-GitHub/googlesearch#34]
https://github.com/Nv7-GitHub/googlesearch/blob/be88ef64de65529e5d42f14b4f2cd3f675ae4adf/googlesearch/__init__.py#L42-L62

Code cannot exit the while loop if the value of `start` never goes up, and the value of `start` only ever goes up if a valid result is yielded.
For search terms that have zero results, this results on the code getting stuck trying to find something forever.

**Comment by binhex** [comment]
Any chance this can get merged in and released?

**Comment by Nv7-GitHub** [comment]
This has been fixed.
