### ISSUE TITLE
Unable to use proxy

### ISSUE THREAD

**Issue by bakadesuyou** [Nv7-GitHub/googlesearch#36]
API_KEY = "2fdb6ced427de857f32870d733fe69b0"
query = "loli"
proxy = f"http://scraperapi.country_code=us:{API_KEY}@proxy-server.scraperapi.com:8001"

loli_links = [link for link in search(term=query, proxy=proxy)]

**Comment by Arsh1219** [comment]
same issue. did you find any solution?

**Comment by eheckard23** [comment]
Gonna assume it has to do with the fact that `proxy` is always being set to `None` no matter if one is being passed or not.

https://github.com/Nv7-GitHub/googlesearch/blob/master/googlesearch/__init__.py#L39-L44

**Comment by Nv7-GitHub** [comment]
It should be set to `{"http": <proxy>}` right after though

**Comment by eheckard23** [comment]
Oof my b, sometimes i swear my dyslexia kicks in lol, proxies and proxy were the same word to me until i looked super close
