### ISSUE TITLE
Quota for the Google Search

### ISSUE THREAD

**Issue by ZorkJ** [Nv7-GitHub/googlesearch#37]
Does this project have any quota that limits how many times we can use in one day or in one minute?

**Comment by Nv7-GitHub** [comment]
You may get a 429 error from google if you've overused it

**Comment by Themis3000** [comment]
There's no real way of knowing how often you can search without getting a 429 response. I've tested it on a bunch of different ip addresses though and as long as you don't have any concurrency (and you have a bit of luck) you can make 1000's of requests in a row no problem. Some ip addresses don't yield such luck though and you'll get a 429 within 10 requests
