### ISSUE TITLE
search result in variable

### ISSUE THREAD

**Issue by VarunBanka** [Nv7-GitHub/googlesearch#38]
in which variable does this module stores final search result ?

**Comment by Themis3000** [comment]
You define what variable you want it stored in. `search()` simply returns the final search results, assign that value to a variable like this:

(results can be called anything else you'd like)
`results = search("test search")`

If you'd like the results in a list use `list()` like this:
`results = list(search("test search"))`

**Comment by VarunBanka** [comment]
> You define what variable you want it stored in. `search()` simply returns the final search results, assign that value to a variable like this:
> 
> (results can be called anything else you'd like) `results = search("test search")`
> 
> If you'd like the results in a list use `list()` like this: `results = list(search("test search"))`


So can I do like this?
print(results)
?
If no then how ?
I'm making a chat bot with voice support so for that I need.......

**Comment by Themis3000** [comment]
That's correct, if you do `results = list(search("test search"))` then you can also do `print(results)`, that's correct

**Comment by VarunBanka** [comment]
> That's correct, if you do `results = list(search("test search"))` then you can also do `print(results)`, that's correct

okay, thanks
