### ISSUE TITLE
search word with quotation

### ISSUE THREAD

**Issue by fazialnjd** [Nv7-GitHub/googlesearch#41]
Hi.
I search in google "laminated glass" and "polyvinyl butyral" and see multiple pages results; but when I send this phrase to googlesearch module; I am not getting any results.
why? and how I can to fix it?
(I am need exact result of this phrase.)
this is my code:
```
    from googlesearch import search

    phrase = '"laminated glass" and "polyvinyl butyral"'
    results = search(phrase)
    res_list = list(results)
```
thanks

**Comment by Nv7-GitHub** [comment]
What does it return? An empty list?

**Comment by frida96** [comment]
> What does it return? An empty list?

Yes. It returns an empty list .

**Comment by Smyja** [comment]
> > What does it return? An empty list?
> 
> Yes. It returns an empty list .

Did you resolve the issue?

**Comment by codemee** [comment]
I think that's the url encoding problem, I've make a pull request to fix this.
#53

**Comment by Nv7-GitHub** [comment]
This should be fixed in the next release then
