### ISSUE TITLE
What a cool module!

### ISSUE THREAD

**Issue by xx-m-h-u-xx** [Nv7-GitHub/googlesearch#5]
Sorry it's not really an issue I'm addressing about.

When using the `googlesearch` module's `search`  function,  can an additional parameter such as specifying a site: `www.wikipedia.com`   _to Google Index_ be accepted? I want to limit the results so that when I execute the `search` function, all related URL links, based on the given query, gets retrieved from sources in the Wikipedia website.

**Comment by sanderjo** [comment]
Do you mean this?

```
>>> for i in search("Google site:wikipedia.com"):
...     print(i)
... 
https://www.wikipedia.com/wiki/Topic-Sensitive_PageRank
https://wikipedia.com/wiki/Google_(verb)
https://en.wikipedia.com/wiki/History_of_Google
https://www.wikipedia.com/wiki/Alphabet_Inc.
https://en.wikipedia.com/wiki/Google_Earth
https://www.wikipedia.com/wiki/Category:Google
https://www.wikipedia.com/wiki/Google_Video
https://www.wikipedia.com/wiki/Waymo
https://en.wikipedia.com/wiki/Googol
https://wikipedia.com/wiki/Google_logo
https://en.wikipedia.com/wiki/Knowledge_Graph
https://en.m.wikipedia.com/wiki/Android_(Operating_System)
https://www.wikipedia.com/wiki/Google_Hangouts
```

**Comment by xx-m-h-u-xx** [comment]
Oooh! So you can add a "site" argument as a parameter to the `googlesearch` function? That's cool ! The documentation should include that.. correct me if I'm wrong, is it stated?

**Comment by sanderjo** [comment]
Well, that is standard Google. Not module stuff.

See https://support.google.com/websearch/answer/2466433 and https://www.spyfu.com/blog/google-search-operators/
