### ISSUE TITLE
Add search country as a parameter

### ISSUE THREAD

**Issue by internetyev** [Nv7-GitHub/googlesearch#55]
Is it possible to specify the country as a parameter?  I see that I  can specify the language, but not the country.

**Comment by Akash-at-LearnTube** [comment]
hey @internetyev did you make any progress on this? I am also looking for the same feature.

**Comment by internetyev** [comment]
@MLninja-2022 unfortunately, no. I switched to another solution.

**Comment by smit-kukadiya** [comment]
@internetyev What is another solution?

**Comment by georgegeorge2525** [comment]
what is another solution?

**Comment by georgegeorge2525** [comment]
probably a proxy?

**Comment by internetyev** [comment]
@smit-kukadiya I used a search API such as DataforSEO. Their Google SERP advanced endpoint allows setting up a country or city, or specific coordinates.

**Comment by Nv7-GitHub** [comment]
I think this needs a proxy or VPN.
