### ISSUE TITLE
Getting the text preview of a search result?

### ISSUE THREAD

**Issue by Nasko-5** [Nv7-GitHub/googlesearch#6]
Is there a way of getting the text preview of a search result? If so, how do i do it? And if not can you implement it?

**Comment by Nv7-GitHub** [comment]
How do you think this should be implemented? Maybe something like 
```
search_advanced("Python")
```
which would return an array of Classes, containing the result title, description, and URL?

**Comment by NoXPhasma** [comment]
I am interested in more information in the response as well and your class approach sounds good to me.

**Comment by Nv7-GitHub** [comment]
Added in 1.1.0!
