### ISSUE TITLE
Returning object generator vice the search result

### ISSUE THREAD

**Issue by Zak-Alford** [Nv7-GitHub/googlesearch#60]
Getting an odd behavior where printing out a list of just the result gives me the usable link that I want, but not the individual result itself (returns the generator object search):

![image](https://github.com/Nv7-GitHub/googlesearch/assets/88165870/b759ae12-9f73-4f78-8a4d-fce6ec426bac)

I can get around what I'm even using this for in the meantime by just looking for the first list entry but don't believe this is intended

**Comment by Nv7-GitHub** [comment]
Use the advanced search
