### ISSUE TITLE
Anyone facing Error 429? Client Error: Too Many Requests

### ISSUE THREAD

**Issue by shuvrobasu** [Nv7-GitHub/googlesearch#61]
I am receiving 429 error after 5 or 6 searches. I know the code does randomly choose a different user agent which shouldn't bring this error, however I did get it. I'm running my script from the command promt and wanted to check if other uses are also facing the same issue. I also do not see any Retry After in the error message which doesn't help.

![image](https://github.com/Nv7-GitHub/googlesearch/assets/81471660/2dcaa976-731d-4d47-aff3-39ab057f4a60)

I would request the community to provide any insights on this or workarounds if any.

Thanks in advance.

**Comment by jason-huanghao** [comment]
I have the same problem of requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url. You may use time.sleep(0.06) in your code to slow down your query

**Comment by shuvrobasu** [comment]
> I have the same problem of requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url. You may use time.sleep(0.06) in your code to slow down your query

Thanks @jason-huanghao .

**Comment by arditobryan** [comment]
I find out there are some queries that make the search function stall for over 1 minute, then they return 429, making the current  IP unusuable.
Ex. "Malaysia sugar tax, RM0.40 (US$0.086) per litre, more than 5 grams/100ml" takes a few seconds to retrieve the first 2 links, but at the 3rd, it makes me wait 1:30 mins, then returns 429, and the IP is unusable.
I tried the same query on Google Colab (that should not use my IP), yet, to be sure, I also tried switching internet connection to the phone hotspot and using an EC2, and all lead to the same results (breaking at the 3rd link of the same query): some queries can break the algorithm

Ideally, we would have a timeout for the requests, but I have not been able to implement it on the current llibrary. Any help is appreciated.

**Comment by shuvrobasu** [comment]
One suggestion would be to randomize the user agent which is already done
in the library but add more user agents and check if same user agent is not
used previously. Adding a delay forcefully before a request can be another
option.

with regards
Shuvro

sent from my mobile device

**Comment by ttuvera1125** [comment]
I am also experiencing the same error. I already tried forcefully adding a delay before a request but it is still returning the same 429 Client Error. 

Can anybody help?

**Comment by ting-chih** [comment]
Same question. How to fix the problem of too many requests?

**Comment by SaiKiru** [comment]
Google flags your code as a potential bot and the link actually shows a captcha to prove you're not. The best way to solve this is to just use their official Custom Search API as you're not allowed to use their search in the way this library does.

**Comment by Nv7-GitHub** [comment]
The user agents are randomized but I believe there is a bug where it sends many queries for some searches. I will investigate this.

**Comment by Nv7-GitHub** [comment]
I am not having this problem when I search "Malaysia sugar tax, RM0.40 (US$0.086) per litre, more than 5 grams/100ml", it sends 2 requests and finds this issue!
