### ISSUE TITLE
Zero Search Result

### ISSUE THREAD

**Issue by arouzbehani** [Nv7-GitHub/googlesearch#64]
there is a case which searching google returns no result ( because of mistyping or other reasons) so there will be an infinite loop in search function:
```
    while start < num_results:
        # Send request
        resp = _req(escaped_term, num_results - start,
                    lang, start, proxies, timeout)

        # Parse
        soup = BeautifulSoup(resp.text, "html.parser")
        result_block = soup.find_all("div", attrs={"class": "g"})
        for result in result_block:
            # Find link, title, description
            link = result.find("a", href=True)
            title = result.find("h3")
            description_box = result.find(
                "div", {"style": "-webkit-line-clamp:2"})
            if description_box:
                description = description_box.text
                if link and title and description:
                    start += 1
                    if advanced:
                        yield SearchResult(link["href"], title.text, description)
                    else:
                        yield link["href"]
        sleep(sleep_interval)
```
the result_block is nothing so the start parameters remains always below num_result
So I add a break point to line before sleep line
```
        if start==0: break
```

**Comment by TheMrguiller** [comment]
I am having the same error but in may case is when searching for an specific paper: "SINAI at SemEval-2021 Task 5: Combining Embeddings in a BiLSTM-CRF model for Toxic Spans Detection". In my case i get some result until it reaches 7, after that it seems its not able to extract anything else so an infinite happens and after some time i get the 429 error.

**Comment by arouzbehani** [comment]
> I am having the same error but in may case is when searching for an specific paper: "SINAI at SemEval-2021 Task 5: Combining Embeddings in a BiLSTM-CRF model for Toxic Spans Detection". In my case i get some result until it reaches 7, after that it seems its not able to extract anything else so an infinite happens and after some time i get the 429 error.

I am not sure but in my case I needed to add this extra modification:
```
            if description_box:
                ...
            else:
                start +=1
```

**Comment by Nv7-GitHub** [comment]
This has been resolved.
