### ISSUE TITLE
The latest release is dependent on a vulnerable dependency

### ISSUE THREAD

**Issue by MohamedKarrab** [Nv7-GitHub/googlesearch#65]
The latest release of googlesearch (1.10) is dependent on a vulnerable dependency Requests==2.25.1, Please update it
![image](https://github.com/Nv7-GitHub/googlesearch/assets/107933631/2bd9e533-cee2-43cc-aee3-c36b18245e9a)

**Comment by Nv7-GitHub** [comment]
This has been fixed!
