### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by SafalAdhikari7** [Nv7-GitHub/googlesearch#68]
The error says: cannot import name 'search' from 'googlesearch'

So, I need help regarding this error.

**Comment by challenge3697** [comment]
Hi, you need to install the module first, open your terminal and run this 
`python3 -m pip install googlesearch-python`

**Comment by jeremystevens** [comment]
@challenge3697  his issue isn't an importing issue,  its the fact that the documentation says from googlesearch import search but there is no function  called search(lowercase) only a class or a least not anymore it used to work fine 6 months ago now something changed I came back to an old project of mine that worked fine before and now it doesn't work i have the same issue.  and its not an import problem
