### ISSUE TITLE
429 Client Error: Too Many Requests for url:

### ISSUE THREAD

**Issue by Minami-su** [Nv7-GitHub/googlesearch#72]
| __main__ | ERROR | An error occurred: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%25E5%25B9%25BF%25E5%25B7%259E%25E5%259F%258E%25E8%2581%258C%25E6%25A0%25A1%25E6%25AD%258C%25E6%2598%25AF%25E4%25BB%2580%25E4%25B9%2588%26num%3D32%26hl%3Dzh%26start%3D0&hl=zh&q=EhAqEM5AAjIAAAFJAQQBcwAJGOLhwKsGIjBQOcAu724Gk5CUqRlfIv2iMkMeCAAldO0d1rnqA2n1AZfcWu_YcGEAdwjNzd-i8PMyAXJaAUM

**Comment by 99starman** [comment]
Hi! Could you share how you resolved this issue? Thanks!

**Comment by RandomUser991** [comment]
Hi !
I am also interested :)
@Minami-su
