### ISSUE TITLE
How can I use proxy in this library.

### ISSUE THREAD

**Issue by idjdnejr** [Nv7-GitHub/googlesearch#73]
I have code like this:

for j in search(usermessage + site, num_results=5, lang='ru', sleep_interval=2, proxy='http://104.26.2.46:80'):
        responce.append(j)

I installed a proxy but it doesn't work.
I saw issues where this topic was raised, but I still didn’t understand how to use a proxy.

**Comment by Nv7-GitHub** [comment]
This has been merged.
