### ISSUE TITLE
Problems with cyrillic symbols

### ISSUE THREAD

**Issue by Roman223** [Nv7-GitHub/googlesearch#84]
The output from following function from ```urllib``` in search function returns nonsence if terms have cycillic symbols. 

```
escaped_term = urllib.parse.quote_plus(term,)
```

Passing encoding (utf8) doesn't solve problem. For my case, I just replaced this row with ```escaped_term = term```.

**Comment by Nv7-GitHub** [comment]
Fixed in the next release! I realized that Requests automatically encodes it so this line doesn't even need to exist.
