### ISSUE TITLE
Can you give an option to limit the date range of Internet lookups

### ISSUE THREAD

**Issue by mjoe67886** [Nv7-GitHub/googlesearch#90]
That way I could get search results that are only after a specific date which is helpful for Googling programmatically error messages. That way you can make sure the results are from the version of the software that you're currently in

**Comment by Nv7-GitHub** [comment]
I believe this can be incorporated into the search query using google's "before:" and "after:" query features

**Comment by mjoe67886** [comment]
Thank you very much for that tip I really appreciate your library and how
it just works immediately and perfectly every time
